### ISSUE TITLE
Unwanted change in required form fields behaviour

### ISSUE THREAD

**Issue by mathieuhinderyckx** [darklow/django-suit#566]
If this is a bug please specify versions you're using first.

Django version: 1.10.5
Django Suit version: 0.2.23
Python version: 2.7

Issue: After upgrading django-suit from 0.2.21 to 0.2.23, there is a change in behaviour. All the lines in a formset in an admin inlines are now required while previously they could be left blank.

**Comment by woeye** [comment]
This is indeed a serious bug. 

If you have a model with some inlines it is no longer possible to edit those using diango suit because the inlines are no longer optional. You must enter data in those inlines or the admin won't let you save your model.

Without django suit everything works just fine, though. 

Workarounds:
- Disable django suit
- Or rollback to django 1.9.x

**Comment by darklow** [comment]
Hmm sorry, I got it wrong, I thought this is for v2, not v1. 
Need to take one more look.

**Comment by darklow** [comment]
Fix included in latest v0.2.24

**Comment by pix666** [comment]
This fix breaks sorting SortableGenericStackedInline.
I have two SortableGenericStackedInline (with same model) on one page at the same time. Ordering on first formset doesn't work (JS sets zeroes at inputs). On second - works fine.

Django: 1.18.18
Django-suit: 0.2.24 and 0.2.25 (0.2.23 - works)

I think the issue is related to incorrect selector for ```$set_block``` (sortables.js):
![img](http://dl4.joxi.net/drive/2017/07/15/0001/2001/75729/29/10a4e1c060.jpg)

In my case, for both formsets selector for ```$set_block``` is <pre>.dynamic-attachable_blocks-attachablereference-content_type-object_id</pre>
But inlines in second formset has class <pre>.dynamic-attachable_blocks-attachablereference-content_type-object_id<b>-2</b></pre>

So, on first fromset ```$set_block``` have DOM element and ordering doesn't works. On second, ```$set_block``` is ```undefined``` and ordering works
![img](http://dl4.joxi.net/drive/2017/07/15/0001/2001/75729/29/539815a78d.jpg)
