### ISSUE TITLE
Menu switching to different item when editing

### ISSUE THREAD

**Issue by gamesbook** [darklow/django-suit#601]
Django version: 1.10.7
Django Suit version: 2a 
Python version: 3.5

When switching from list view to edit view, the menu shifts from the currently selected item to a new one.

![list_view](https://cloud.githubusercontent.com/assets/354027/24962046/feb2d256-1f9a-11e7-9c4b-0f6a559e35c3.png)

![edit_view](https://cloud.githubusercontent.com/assets/354027/24962055/046667bc-1f9b-11e7-9477-7de9d434bd25.png)

**Comment by ebertti** [comment]
Do you have this PR in your version? https://github.com/darklow/django-suit/pull/590

**Comment by gamesbook** [comment]
@ebertti Are you asking @darklow ?  I downloaded the tarball a few hours ago ...

**Comment by ebertti** [comment]
@gamesbook for you 😄 I made this PR

Take a look on this issue, https://github.com/darklow/django-suit/issues/587

Can you send the same information then @darklow asked to me? Maybe I can help you.

**Comment by gamesbook** [comment]
@ebertti @darklow  asked for this `Please post your full config of Django Suit and URL addresses of both list and adding new item pages.` As you said, URL are not the problem, and I don't have any Django Suit config apart from the default.

**Comment by darklow** [comment]
PR @ebertti mentioned was merged in 5 days ago. Really weird that you are experiencing same problems he fixed in PR. As a quick workaround until fix is there you can define your models separately, sooner or later you will want to reorder them anyways or add something else into same parent. I usually group ChildItems manually based on the logical groups from different apps instead of just defining apps as parent, for example: Content, Users, Reports, Settings, etc. But I will take a look and see how to fix problem.

@gamesbook Could you post your menu config?

**Comment by gamesbook** [comment]
@darklow I don't have a menu config yet.  Still working with the most minimal suit settings possible.

**Comment by darklow** [comment]
Should be fixed now.
```
pip uninstall django-suit
pip install https://github.com/darklow/django-suit/tarball/v2
```

**Comment by gamesbook** [comment]
Working.
