### ISSUE TITLE
Import Export style error in suit2.0

### ISSUE THREAD

**Issue by larryhq** [darklow/django-suit#606]
If this is a bug please specify versions you're using first.

Django version: 1.10.7
Django Suit version: v2
Python version: python3.5

Issue:
my admin code:
```
class SuperAdmin(ExportMixin, admin.ModelAdmin):
```
![](https://test-media-cmcaifu-com.oss-cn-hangzhou.aliyuncs.com/upload/a6460e0cbc014bc6b94cdb8f3fc719bb.png)

**Comment by darklow** [comment]
I have no idea what `ExportMixin` is.
Does it work when you remove `ExportMixin` from admin class?

**Comment by larryhq** [comment]
ExportMixin is from django-import-export lib
If I remove ExportMixin from admin class , export will be not work.
The suit1.x style is ok like 
![](https://test-media-cmcaifu-com.oss-cn-hangzhou.aliyuncs.com/upload/114a0c87c71743f6b7231effce802f80.png)

**Comment by tabl** [comment]
I also got this glitch.

Django version: 1.11
Django Suit version: v2
Python version: python 2.7.8

![image](https://cloud.githubusercontent.com/assets/3210349/25657632/795320a2-3007-11e7-9836-01f8d5c04f78.png)

**Comment by tabl** [comment]
Got a fix for that. The issue is there is an incorrect **class** in body tag.
Solution:
replace
`{% block bodyclass %}{{ opts.app_label }}-{{ opts.object_name.lower }} change-form{% endblock %}`
to
`{% block bodyclass %}suit_toggle_changelist_top_actions suit_form_submit_on_right suit_layout_horizontal app-loyal_daisy model-client change-list change-form{% endblock %}`
in /site-packages/import_export/templates/admin/import_export/base.html

**Comment by larryhq** [comment]
@tabl  Fix it, thank you very much.
